from . import regex
from .finder import Match
from .finder import Pattern
from .finder import SureMatch
from .finder import compile
from .finder import fullmatch
from .finder import match
from .finder import search
from .manipulator import TextManipulator
from .manipulator import manipulate
from .manipulator import substitute
from .slicer import SemanticSlicer
from .slicer import slice
from .wrapper import wrap
from .wrapper import dedent
from .wrapper import join
