from lk_utils import dedent
from lk_utils import fs
from lk_utils import manipulate_text
from lk_utils import now
from lk_utils import run_cmd_args
from lk_utils import __version__
from neoprint import print

run_cmd_args(
    (
        'uv',
        'export',
        '--format',
        'requirements.txt',
        '--no-hashes',
        '-o',
        'requirements.lock',
        '--locked',
    )
)

file = 'requirements.lock'
text = fs.load(file, 'plain')
text = (
    manipulate_text(text)
    .cut()
    .find('-e .\n')
    .then_cut()
    .replace('')
    .prepend(
        dedent(
            """
            # This file was auto generated by pyproject-manager.
            # File was updated at {UPDATE_TIME}
            # Use pip to install:
            #   pip install -U -r {FILENAME} --no-deps

            """,
            rstrip=False,
        ).format(UPDATE_TIME=now('y.m.d h:n:s'), FILENAME='requirements.lock')
    )
    .then_insert(
        dedent(
            """
            --index-url {PRIMIARY_SOURCE}
            --extra-index-url {SECONDARY_SOURCE}
            --trusted-host {TRUSTED_HOST}

            """,
            rstrip=False,
        ).format(
            PRIMIARY_SOURCE='https://pypi.tuna.tsinghua.edu.cn/simple',
            SECONDARY_SOURCE='http://localhost:2131',
            TRUSTED_HOST='localhost',
        )
    )
    .then_insert(
        'lk-utils @ http://localhost:2131/lk-utils/lk_utils-{}-py3-none-any.whl'
        '\n\n'.format(__version__)
    )
    .end()
    .subx_all(
        r'([-\w]+)==([.\w]+).*',
        lambda x: (
            '{} @ {}'.format(
                x.group(1),
                'http://localhost:2131/{}/{}-{}-py3-none-any.whl'.format(
                    x.group(1), x.group(1).replace('-', '_'), x.group(2)
                ),
            )
            if x.group(1) == 'neoprint'
            else x.group()
        ),
    )
    .output()
)
fs.dump(text, file, 'plain')
print('see "<project>/requirements.lock"', ':v4')
